name: checks

on: [ push, pull_request ]

jobs:
  python-black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        uses: libratbag/libratbag/.github/actions/pkginstall@master
        with:
          apt: pkg-config python3-pip python3-gi libgirepository1.0-dev
          pip: attrs black pyudev pygobject git+https://gitlab.freedesktop.org/libevdev/hid-tools
      - name: run Python black
        run: git ls-files | grep ".py" | xargs black
      - name: diff for changes
        run: git diff --exit-code

  pytest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        uses: libratbag/libratbag/.github/actions/pkginstall@master
        with:
          apt: pkg-config python3-pip python3-gi libgirepository1.0-dev libevdev2
          pip: attrs pytest pyudev pygobject libevdev git+https://gitlab.freedesktop.org/libevdev/hid-tools
      - name: run test suite
        run: pytest -v

  mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        uses: libratbag/libratbag/.github/actions/pkginstall@master
        with:
          apt: pkg-config python3-pip python3-gi libgirepository1.0-dev libevdev2
          pip: attrs mypy pytest pyudev pygobject libevdev git+https://gitlab.freedesktop.org/libevdev/hid-tools
      - name: install mypy types
        run: mypy --non-interactive --install-types ratbag tests
      - name: run test suite
        run: mypy ratbag tests
